#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake src/alphatWallFunction
wmake src/thermophysicalModels/specie
wmake src/thermophysicalModels/thermophysicalProperties
wmake src/thermophysicalModels/basic
wmake src/CanteraMixture
wmake src/dfChemistryModel
wmake src/fvModels
wmake src/lagrangian/parcel
wmake src/lagrangian/parcelTurbulence

wmake applications/solvers/df0DFoam
wmake applications/solvers/dfLowMachFoam
wmake applications/solvers/dfHighSpeedFoam

wmake applications/utilities/flameSpeed
